### ISSUE TITLE
The type or namespace Camera doesn't exist in the namespace "Com.Dynamsoft"

### ISSUE THREAD

**Issue by charyjagdeesh** [Dynamsoft/xamarin#23]
I am facing **Camera doesn't exist in the namespace "Com.Dynamsoft"** issue after updating the NuGet package version to **v8.0.0**

![image](https://user-images.githubusercontent.com/39457922/103643203-49eff880-4f7a-11eb-918e-13846a8942b2.png)

**Comment by zyunique** [comment]
> I am facing **Camera doesn't exist in the namespace "Com.Dynamsoft"** issue after updating the NuGet package version to **v8.0.0**
> 
> ![image](https://user-images.githubusercontent.com/39457922/103643203-49eff880-4f7a-11eb-918e-13846a8942b2.png)

fixed
